# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HazelCli < Formula
  desc "Filesystem-first project work queue with a lightweight web UI."
  homepage "https://github.com/flip-z/hazel"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/flip-z/hazel/releases/download/v0.1.3/hazel_0.1.3_darwin_amd64.tar.gz"
      sha256 "82731b3b2abf76b245b904774b123c0ec4ac895deae106a9430cfff0e029e0c1"

      def install
        bin.install "hazel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/flip-z/hazel/releases/download/v0.1.3/hazel_0.1.3_darwin_arm64.tar.gz"
      sha256 "4ce063dd52311005427bd5b54cb421817f1086097baa2a25552d83e42005007f"

      def install
        bin.install "hazel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/flip-z/hazel/releases/download/v0.1.3/hazel_0.1.3_linux_amd64.tar.gz"
      sha256 "64ff7b2d6bb1d28ef2c77808615a2c2d3cbb54717b61ae906ef8189f60d0465f"
      def install
        bin.install "hazel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/flip-z/hazel/releases/download/v0.1.3/hazel_0.1.3_linux_arm64.tar.gz"
      sha256 "6b02c6de36eb4079e94a90c7fc5abed5d0dfdce3c1c277730cc90c6a70ff9129"
      def install
        bin.install "hazel"
      end
    end
  end

  test do
    system "#{bin}/hazel", "--help"
  end
end
