# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hazel < Formula
  desc "Filesystem-first project work queue with a lightweight web UI."
  homepage "https://github.com/flip-z/hazel"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/flip-z/hazel/releases/download/v0.1.1/hazel_0.1.1_darwin_amd64.tar.gz"
      sha256 "6291d44c3298cd1e5409c02ec18c88afd42ff979852140fb97e2d9c103b37347"

      def install
        bin.install "hazel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/flip-z/hazel/releases/download/v0.1.1/hazel_0.1.1_darwin_arm64.tar.gz"
      sha256 "0d6cc17c7ea3109850024959c3a9d7eb44022bb825a6167685993f0b327bbf40"

      def install
        bin.install "hazel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/flip-z/hazel/releases/download/v0.1.1/hazel_0.1.1_linux_amd64.tar.gz"
      sha256 "9a87a4ded60aa85a38e4021c92ce9c116f79f60eb58ff04e82d2b69f1e9dfa05"
      def install
        bin.install "hazel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/flip-z/hazel/releases/download/v0.1.1/hazel_0.1.1_linux_arm64.tar.gz"
      sha256 "6f7d6bd64997f71b600fd6695940a5d19a75b50498de92f56d97ffae4cb860a6"
      def install
        bin.install "hazel"
      end
    end
  end

  test do
    system "#{bin}/hazel", "--help"
  end
end
