# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HazelCli < Formula
  desc "Filesystem-first project work queue with a lightweight web UI."
  homepage "https://github.com/flip-z/hazel"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/flip-z/hazel/releases/download/v0.1.2/hazel_0.1.2_darwin_amd64.tar.gz"
      sha256 "a8e2de918ee0f47cd2dd1dcfd639954de6ad3c6048f8c8015c724c2716d65e2d"

      def install
        bin.install "hazel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/flip-z/hazel/releases/download/v0.1.2/hazel_0.1.2_darwin_arm64.tar.gz"
      sha256 "34d6acce83df757ca19b53a14c77710bbda4576a17cd0177063d9182dd4b8e69"

      def install
        bin.install "hazel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/flip-z/hazel/releases/download/v0.1.2/hazel_0.1.2_linux_amd64.tar.gz"
      sha256 "fa677b81b2f3b01f4a357ebc56f87f33f2efa26d52e33454e177bca0b1da2d5d"
      def install
        bin.install "hazel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/flip-z/hazel/releases/download/v0.1.2/hazel_0.1.2_linux_arm64.tar.gz"
      sha256 "c6df64152cbe0daec5ca810207c69c5c781a3c12bb2dc999fd0b2a053ca751c7"
      def install
        bin.install "hazel"
      end
    end
  end

  test do
    system "#{bin}/hazel", "--help"
  end
end
